"""Article figure delivery — single source of truth for the 17 MDPI article figures.

Verify PDFs exist in a source directory and create symlinks (or copies) in the
article figures directory so LaTeX can include them. The manifest below is the
canonical list; scripts and docs should reference this module.

Usage:
    python -m src.visualization.article_delivery              # verify + symlink
    python -m src.visualization.article_delivery --check-only  # verify only
    python -m src.visualization.article_delivery --copy      # copy instead of symlink
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import List, Tuple

# Single source of truth: 17 article figure basenames (no .pdf).
# Order matches the LaTeX \begin{figure} sequence in articles/clop_dit_biology.tex,
# which determines the auto-numbered Figure 1–17.
#
# SOURCE_BASENAMES: filenames generated by the visualization code in results/figures/.
# ARTICLE_FIGURE_BASENAMES: numbered display names used for symlinks in articles/figures/
#   and for \includegraphics in LaTeX.  The figNN_ prefix makes the article figure
#   number immediately obvious.

_SOURCE_BASENAMES: List[str] = [
    "fig_architecture",              # Fig 1  — Architecture overview
    "fig_training_dynamics",         # Fig 2  — Merged A+C (CLOP + DiT training)
    "fig_embedding_space",           # Fig 3  — Merged B+E (embedding space)
    "panel_d_metrics_summary",       # Fig 4  — Metrics dashboard
    "panel_g_per_type_generation",   # Fig 5  — Per-type generation fidelity
    "panel_f_text_cell_heatmap",     # Fig 6  — Text-cell alignment heatmap
    "panel_n_marker_gene_comparison",# Fig 7  — Marker gene comparison
    "panel_h_expression_correlation",# Fig 8  — Expression correlation
    "panel_i_expression_analysis",   # Fig 9  — Expression analysis
    "panel_m_conditioning_umap",     # Fig 10 — Conditioning landscape
    "panel_j_diversity_diagnostics", # Fig 11 — Diversity diagnostics
    "panel_l_noise_tradeoff",        # Fig 12 — Noise-scale trade-off
    "panel_k_expression_diversity",  # Fig 13 — Expression diversity
    "panel_o_baseline_comparison",   # Fig 14 — Baseline comparison
    "panel_s_benchmark",             # Fig 15 — Composite benchmark
    "fig_downstream_pq",             # Fig 16 — Merged P+Q (downstream clustering + classifier)
    "panel_r_de_concordance",        # Fig 17 — DE concordance
]

ARTICLE_FIGURE_BASENAMES: List[str] = [
    "fig01_architecture",            # Fig 1  — Architecture overview
    "fig02_training_dynamics",       # Fig 2  — Merged A+C (CLOP + DiT training)
    "fig03_embedding_space",         # Fig 3  — Merged B+E (embedding space)
    "fig04_metrics_summary",         # Fig 4  — Metrics dashboard
    "fig05_per_type_generation",     # Fig 5  — Per-type generation fidelity
    "fig06_text_cell_heatmap",       # Fig 6  — Text-cell alignment heatmap
    "fig07_marker_gene_comparison",  # Fig 7  — Marker gene comparison
    "fig08_expression_correlation",  # Fig 8  — Expression correlation
    "fig09_expression_analysis",     # Fig 9  — Expression analysis
    "fig10_conditioning_umap",       # Fig 10 — Conditioning landscape
    "fig11_diversity_diagnostics",   # Fig 11 — Diversity diagnostics
    "fig12_noise_tradeoff",          # Fig 12 — Noise-scale trade-off
    "fig13_expression_diversity",    # Fig 13 — Expression diversity
    "fig14_baseline_comparison",     # Fig 14 — Baseline comparison
    "fig15_benchmark",               # Fig 15 — Composite benchmark
    "fig16_downstream_pq",           # Fig 16 — Merged P+Q (downstream clustering + classifier)
    "fig17_de_concordance",          # Fig 17 — DE concordance
]

# Map from numbered display name → source filename generated by the visualization code.
_SOURCE_MAP = dict(zip(ARTICLE_FIGURE_BASENAMES, _SOURCE_BASENAMES))

# Basename -> producer file path (relative to repo root). Used for presentation-policy tests.
# Must match FIGURE_ORGANIZATION.md "Canonical producers" table. Order matches Fig 1–17.
ARTICLE_FIGURE_PRODUCERS: List[Tuple[str, str]] = [
    ("fig01_architecture", "scripts/analysis/generate_architecture_figure.py"),       # Fig 1
    ("fig02_training_dynamics", "src/visualization/panels_training.py"),              # Fig 2
    ("fig03_embedding_space", "src/visualization/panels_merged.py"),                  # Fig 3
    ("fig04_metrics_summary", "src/visualization/panels_metrics.py"),                 # Fig 4
    ("fig05_per_type_generation", "src/visualization/results_visualizer.py"),         # Fig 5
    ("fig06_text_cell_heatmap", "src/visualization/results_visualizer.py"),           # Fig 6
    ("fig07_marker_gene_comparison", "src/visualization/panels_expression.py"),       # Fig 7
    ("fig08_expression_correlation", "src/visualization/panels_expression.py"),       # Fig 8
    ("fig09_expression_analysis", "src/visualization/panels_expression.py"),          # Fig 9
    ("fig10_conditioning_umap", "scripts/analysis/conditioning_analysis.py"),         # Fig 10
    ("fig11_diversity_diagnostics", "scripts/analysis/diversity_diagnostics.py"),     # Fig 11
    ("fig12_noise_tradeoff", "scripts/analysis/diversity_diagnostics.py"),            # Fig 12
    ("fig13_expression_diversity", "scripts/analysis/diversity_diagnostics.py"),      # Fig 13
    ("fig14_baseline_comparison", "src/visualization/baseline_panels.py"),            # Fig 14
    ("fig15_benchmark", "src/visualization/benchmark_panels.py"),                     # Fig 15
    ("fig16_downstream_pq", "src/visualization/downstream_panels.py"),               # Fig 16
    ("fig17_de_concordance", "src/visualization/panels_de_concordance.py"),           # Fig 17
]


def deliver_figures(
    source_dir: Path,
    target_dir: Path,
    *,
    symlink: bool = True,
    check_only: bool = False,
) -> bool:
    """Verify all article figure PDFs exist in source_dir and optionally link/copy to target_dir.

    Parameters
    ----------
    source_dir : directory containing the generated PDFs (e.g. results/figures)
    target_dir : directory for the article (e.g. articles/figures)
    symlink : if True, create symlinks; if False, copy files (ignored when check_only=True)
    check_only : if True, only verify presence in source_dir; do not modify target_dir

    Returns
    -------
    True if all 17 PDFs are present (and, when not check_only, successfully linked/copied).
    """
    source_dir = Path(source_dir).resolve()
    target_dir = Path(target_dir).resolve()

    missing: List[str] = []
    for article_base in ARTICLE_FIGURE_BASENAMES:
        source_base = _SOURCE_MAP[article_base]
        path = source_dir / f"{source_base}.pdf"
        if not path.is_file():
            missing.append(f"{source_base}.pdf (→ {article_base})")
    if missing:
        print(f"Missing {len(missing)} of {len(ARTICLE_FIGURE_BASENAMES)} article figure PDFs in {source_dir}:", file=sys.stderr)
        for m in missing:
            print(f"  MISSING: {m}", file=sys.stderr)
        return False

    if check_only:
        return True

    target_dir.mkdir(parents=True, exist_ok=True)
    for article_base in ARTICLE_FIGURE_BASENAMES:
        source_base = _SOURCE_MAP[article_base]
        src = source_dir / f"{source_base}.pdf"
        dst = target_dir / f"{article_base}.pdf"
        if symlink:
            if dst.exists() or dst.is_symlink():
                dst.unlink()
            dst.symlink_to(src.resolve())
        else:
            shutil.copy2(src, dst)
    return True


def _default_dirs():
    """Default source/target dirs without importing src.utils (avoids pulling in torch)."""
    import os
    root = Path(__file__).resolve().parent.parent.parent
    source = Path(os.environ.get("CLOPDIT_FIG_DIR", str(root / "results" / "figures")))
    target = Path(os.environ.get("CLOPDIT_ARTICLE_FIGURES_DIR", str(root / "articles" / "figures")))
    return source, target


def main() -> int:
    default_source, default_target = _default_dirs()
    parser = argparse.ArgumentParser(
        description="Verify article figure PDFs and create symlinks (or copies) in the article figures directory."
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Only verify all 17 PDFs exist in source dir; do not create symlinks/copies",
    )
    parser.add_argument(
        "--copy",
        action="store_true",
        help="Copy files instead of creating symlinks (default: symlink)",
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=None,
        help=f"Source directory with generated PDFs (default: {default_source})",
    )
    parser.add_argument(
        "--target-dir",
        type=Path,
        default=None,
        help=f"Target directory for article figures (default: {default_target})",
    )
    args = parser.parse_args()

    source = args.source_dir if args.source_dir is not None else default_source
    target = args.target_dir if args.target_dir is not None else default_target

    if args.check_only:
        print(f"Checking {len(ARTICLE_FIGURE_BASENAMES)} article figures in {source}...")
        ok = deliver_figures(source, target, symlink=True, check_only=True)
        if ok:
            print("  All 17 PDFs present.")
        else:
            print("Run 'bash scripts/regenerate_report.sh' to generate them.", file=sys.stderr)
        return 0 if ok else 1

    print(f"Checking {len(ARTICLE_FIGURE_BASENAMES)} article figures in {source}...")
    ok = deliver_figures(source, target, symlink=not args.copy, check_only=False)
    if not ok:
        print("Run 'bash scripts/regenerate_report.sh' to generate them.", file=sys.stderr)
        return 1
    print("  All 17 PDFs present.")
    mode = "copied" if args.copy else "symlinked"
    print(f"  17 figures {mode} in {target}.")
    print("")
    print("All 17 article figures verified and symlinked." if not args.copy else "All 17 article figures verified and copied.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
