"""Article figure delivery — single source of truth for the 30 MDPI article figures.

Verify PDF figure assets exist in a source directory and copy them
to the article figures directory so LaTeX can include the PDF
assets directly. The manifest below is the canonical list;
scripts and docs should reference this module.

Usage:
    python -m src.visualization.article_delivery              # verify + symlink
    python -m src.visualization.article_delivery --check-only  # verify only
    python -m src.visualization.article_delivery --copy      # copy instead of symlink
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Tuple

# Single source of truth: 30 article figure basenames (no suffix).
# Order matches the LaTeX \begin{figure} sequence in articles/clop_dit_biology.tex,
# which determines the auto-numbered Figure 1–20.
#
# SOURCE_BASENAMES: filenames generated by visualization code in results/figures/.
# ARTICLE_FIGURE_BASENAMES: numbered display names used for symlinks in articles/figures/
#   and for \includegraphics in LaTeX.

_SOURCE_BASENAMES: List[str] = [
    "fig_architecture",              # Fig 1  — Architecture overview (external script)
    "fig_evaluation_pipeline",       # Fig 2  — Evaluation pipeline schematic (external script)
    "fig03_training_dynamics",       # Fig 3  — Merged A+C (CLOP + DiT training)
    "fig04_embedding_space",         # Fig 4  — Merged B+E (embedding space)
    "fig05_metrics_summary",         # Fig 5  — Metrics dashboard
    "fig06_per_type_fidelity",       # Fig 6  — Per-type generation fidelity
    "fig07_text_cell_alignment",     # Fig 7  — Text-cell alignment heatmap
    "fig08_marker_genes",            # Fig 8  — Marker gene comparison
    "fig09_expression_correlation",  # Fig 9  — Expression correlation
    "fig10_expression_analysis",     # Fig 10 — Expression analysis
    "fig11_conditioning_umap",       # Fig 11 — Conditioning landscape
    "fig12_diversity_diagnostics",   # Fig 12 — Diversity diagnostics
    "fig13_noise_tradeoff",          # Fig 13 — Noise-scale trade-off
    "fig14_expression_diversity",    # Fig 14 — Expression diversity
    "fig15_baseline_comparison",     # Fig 15 — Baseline comparison
    "fig16_benchmark",               # Fig 16 — Composite benchmark
    "fig17_downstream_pq",           # Fig 17 — Merged P+Q (downstream clustering + classifier)
    "fig18_de_concordance",          # Fig 18 — DE concordance
    "fig19_variance_matching_pilot", # Fig 19 — Variance matching pilot (external script)
    "fig20_gene_gene_correlation",   # Fig 20 — Gene-gene correlation (external script)
    "fig21_ablation_heatmap",        # Fig 21 — Ablation comparison heatmap
    "fig22_multi_seed_robustness",   # Fig 22 — Multi-seed robustness
    "fig23_ood_showcase",            # Fig 23 — OOD generation showcase
    "fig24_variance_deepdive",       # Fig 24 — Per-gene variance deep-dive
    "fig25_cross_dataset",             # Fig 25 — Cross-dataset biological validation
    "fig26_expanded_de",               # Fig 26 — Expanded DE concordance
    "fig27_ood_robustness",            # Fig 27 — OOD robustness evaluation
    "fig28_marker_completeness",       # Fig 28 — Marker gene program completeness
    "fig29_embedding_augmentation",    # Fig 29 — Embedding-level augmentation analysis
    "fig30_validation_summary",        # Fig 30 — Multi-experiment validation synthesis
]

ARTICLE_FIGURE_BASENAMES: List[str] = [
    "fig01_architecture",            # Fig 1  — Architecture overview
    "fig02_evaluation_pipeline",     # Fig 2  — Evaluation pipeline schematic
    "fig03_training_dynamics",       # Fig 3  — Merged A+C (CLOP + DiT training)
    "fig04_embedding_space",         # Fig 4  — Merged B+E (embedding space)
    "fig05_metrics_summary",         # Fig 5  — Metrics dashboard
    "fig06_per_type_fidelity",       # Fig 6  — Per-type generation fidelity
    "fig07_text_cell_alignment",     # Fig 7  — Text-cell alignment heatmap
    "fig08_marker_genes",            # Fig 8  — Marker gene comparison
    "fig09_expression_correlation",  # Fig 9  — Expression correlation
    "fig10_expression_analysis",     # Fig 10 — Expression analysis
    "fig11_conditioning_umap",       # Fig 11 — Conditioning landscape
    "fig12_diversity_diagnostics",   # Fig 12 — Diversity diagnostics
    "fig13_noise_tradeoff",          # Fig 13 — Noise-scale trade-off
    "fig14_expression_diversity",    # Fig 14 — Expression diversity
    "fig15_baseline_comparison",     # Fig 15 — Baseline comparison
    "fig16_benchmark",               # Fig 16 — Composite benchmark
    "fig17_downstream_pq",           # Fig 17 — Merged P+Q (downstream clustering + classifier)
    "fig18_de_concordance",          # Fig 18 — DE concordance
    "fig19_variance_matching_pilot", # Fig 19 — Variance matching pilot
    "fig20_gene_gene_correlation",   # Fig 20 — Gene-gene correlation
    "fig21_ablation_heatmap",        # Fig 21 — Ablation comparison heatmap
    "fig22_multi_seed_robustness",   # Fig 22 — Multi-seed robustness
    "fig23_ood_showcase",            # Fig 23 — OOD generation showcase
    "fig24_variance_deepdive",       # Fig 24 — Per-gene variance deep-dive
    "fig25_cross_dataset",             # Fig 25 — Cross-dataset biological validation
    "fig26_expanded_de",               # Fig 26 — Expanded DE concordance
    "fig27_ood_robustness",            # Fig 27 — OOD robustness evaluation
    "fig28_marker_completeness",       # Fig 28 — Marker gene program completeness
    "fig29_embedding_augmentation",    # Fig 29 — Embedding-level augmentation analysis
    "fig30_validation_summary",        # Fig 30 — Multi-experiment validation synthesis
]

# Map from numbered display name → source filename generated by the visualization code.
_SOURCE_MAP = dict(zip(ARTICLE_FIGURE_BASENAMES, _SOURCE_BASENAMES))

# Basename -> producer file path (relative to repo root). Order matches Fig 1–20.
ARTICLE_FIGURE_PRODUCERS: List[Tuple[str, str]] = [
    ("fig01_architecture", "scripts/analysis/generate_architecture_figure.py"),       # Fig 1
    ("fig02_evaluation_pipeline", "scripts/analysis/evaluation_pipeline_figure.py"),  # Fig 2
    ("fig03_training_dynamics", "src/visualization/fig03_training.py"),               # Fig 3
    ("fig04_embedding_space", "src/visualization/fig04_embedding.py"),                # Fig 4
    ("fig05_metrics_summary", "src/visualization/fig05_metrics.py"),                  # Fig 5
    ("fig06_per_type_fidelity", "src/visualization/fig06_fidelity.py"),               # Fig 6
    ("fig07_text_cell_alignment", "src/visualization/fig07_alignment.py"),            # Fig 7
    ("fig08_marker_genes", "src/visualization/fig08_markers.py"),                     # Fig 8
    ("fig09_expression_correlation", "src/visualization/fig09_expression_corr.py"),   # Fig 9
    ("fig10_expression_analysis", "src/visualization/fig10_expression_analysis.py"),  # Fig 10
    ("fig11_conditioning_umap", "src/visualization/fig11_conditioning.py"),           # Fig 11
    ("fig12_diversity_diagnostics", "src/visualization/fig12_diversity.py"),          # Fig 12
    ("fig13_noise_tradeoff", "src/visualization/fig13_noise_tradeoff.py"),            # Fig 13
    ("fig14_expression_diversity", "src/visualization/fig14_expr_diversity.py"),      # Fig 14
    ("fig15_baseline_comparison", "src/visualization/fig15_baselines.py"),            # Fig 15
    ("fig16_benchmark", "src/visualization/fig16_benchmark.py"),                      # Fig 16
    ("fig17_downstream_pq", "src/visualization/fig17_downstream.py"),                # Fig 17
    ("fig18_de_concordance", "src/visualization/fig18_de_concordance.py"),            # Fig 18
    ("fig19_variance_matching_pilot", "scripts/analysis/variance_matching_pilot.py"), # Fig 19
    ("fig20_gene_gene_correlation", "scripts/analysis/gene_gene_correlation.py"),     # Fig 20
    ("fig21_ablation_heatmap", "src/visualization/fig21_ablation_heatmap.py"),        # Fig 21
    ("fig22_multi_seed_robustness", "src/visualization/fig22_multi_seed.py"),         # Fig 22
    ("fig23_ood_showcase", "src/visualization/fig23_ood_showcase.py"),                # Fig 23
    ("fig24_variance_deepdive", "src/visualization/fig24_variance_deepdive.py"),      # Fig 24
    ("fig25_cross_dataset", "src/visualization/fig25_cross_dataset.py"),              # Fig 25
    ("fig26_expanded_de", "src/visualization/fig26_expanded_de.py"),                  # Fig 26
    ("fig27_ood_robustness", "src/visualization/fig27_ood_robustness.py"),            # Fig 27
    ("fig28_marker_completeness", "src/visualization/fig28_marker_completeness.py"),  # Fig 28
    ("fig29_embedding_augmentation", "src/visualization/fig29_embedding_augmentation.py"),  # Fig 29
    ("fig30_validation_summary", "src/visualization/fig30_validation_summary.py"),    # Fig 30
]

_N_FIGURES = len(ARTICLE_FIGURE_BASENAMES)
_ARTICLE_INCLUDE_SUFFIX = ".pdf"
_SOURCE_REQUIRED_SUFFIXES = (".pdf",)
_TARGET_DELIVERY_SUFFIXES = (".pdf",)
_PREVIEW_SUFFIXES = {".jpg"}
_SOURCE_SUFFIXES = {".pdf", ".jpg", ".jpeg", ".png"}
_TARGET_SUFFIXES = {".pdf", ".jpg", ".jpeg", ".png"}
_TARGET_KEEP_NAMES = {"README.md"}


def expected_source_artifacts(*, keep_preview: bool = False) -> set[str]:
    """Return the canonical generated figure artifacts in ``results/figures``."""
    suffixes = {".pdf"}
    if keep_preview:
        suffixes.update(_PREVIEW_SUFFIXES)
    return {f"{source_base}{suffix}" for source_base in _SOURCE_BASENAMES for suffix in suffixes}


def expected_target_artifacts() -> set[str]:
    """Return the canonical article-facing artifacts in ``articles/figures``."""
    return {
        f"{article_base}{suffix}"
        for article_base in ARTICLE_FIGURE_BASENAMES
        for suffix in _TARGET_DELIVERY_SUFFIXES
    } | _TARGET_KEEP_NAMES


def cleanup_legacy_artifacts(
    source_dir: Path,
    target_dir: Path,
    *,
    keep_preview: bool = True,
) -> Dict[str, list[str]]:
    """Remove stale figure artifacts outside the canonical manifest.

    Returns a summary mapping ``source_removed`` / ``target_removed`` to the
    deleted filenames.
    """
    source_dir = Path(source_dir).resolve()
    target_dir = Path(target_dir).resolve()

    source_keep = expected_source_artifacts(keep_preview=keep_preview)
    target_keep = expected_target_artifacts()
    removed = {"source_removed": [], "target_removed": []}

    if source_dir.exists():
        for item in sorted(source_dir.iterdir()):
            if not item.is_file():
                continue
            if item.suffix.lower() not in _SOURCE_SUFFIXES:
                continue
            if not (item.stem.startswith("fig") or item.name == "clop_dit_full_report.pdf"):
                continue
            if item.name in source_keep:
                continue
            item.unlink()
            removed["source_removed"].append(item.name)

    if target_dir.exists():
        for item in sorted(target_dir.iterdir()):
            if item.name in target_keep:
                continue
            if item.suffix.lower() not in _TARGET_SUFFIXES:
                continue
            if not (item.stem.startswith("fig") or item.is_symlink()):
                continue
            item.unlink()
            removed["target_removed"].append(item.name)

    return removed


def deliver_figures(
    source_dir: Path,
    target_dir: Path,
    *,
    symlink: bool = False,
    check_only: bool = False,
    cleanup: bool = False,
    keep_preview: bool = True,
) -> bool:
    """Verify all article figure PDFs exist in source_dir and optionally copy to target_dir.

    Parameters
    ----------
    source_dir : directory containing the generated figures (e.g. results/figures)
    target_dir : directory for the article (e.g. articles/figures)
    symlink : if True, create symlinks; if False, copy files (ignored when check_only=True)
    check_only : if True, only verify presence in source_dir; do not modify target_dir

    Returns
    -------
    True if all required PDFs are present (and, when not check_only,
    successfully linked/copied).
    """
    source_dir = Path(source_dir).resolve()
    target_dir = Path(target_dir).resolve()

    missing: List[str] = []
    for article_base in ARTICLE_FIGURE_BASENAMES:
        source_base = _SOURCE_MAP[article_base]
        for suffix in _SOURCE_REQUIRED_SUFFIXES:
            path = source_dir / f"{source_base}{suffix}"
            if not path.is_file():
                missing.append(f"{source_base}{suffix} (→ {article_base}{suffix})")
    if missing:
        print(
            f"Missing {len(missing)} required article figure assets across {_N_FIGURES} figures in {source_dir}:",
            file=sys.stderr,
        )
        for m in missing:
            print(f"  MISSING: {m}", file=sys.stderr)
        return False

    if check_only:
        return True

    target_dir.mkdir(parents=True, exist_ok=True)
    if cleanup:
        removed = cleanup_legacy_artifacts(source_dir, target_dir, keep_preview=keep_preview)
        for category, names in removed.items():
            if names:
                print(f"  Cleaned {category}: {', '.join(names)}")
    for article_base in ARTICLE_FIGURE_BASENAMES:
        source_base = _SOURCE_MAP[article_base]
        for suffix in _TARGET_DELIVERY_SUFFIXES:
            src = source_dir / f"{source_base}{suffix}"
            dst = target_dir / f"{article_base}{suffix}"
            if symlink:
                if dst.exists() or dst.is_symlink():
                    dst.unlink()
                dst.symlink_to(src.resolve())
            else:
                shutil.copy2(src, dst)
    return True


def _default_dirs():
    """Default source/target dirs without importing src.utils (avoids pulling in torch)."""
    import os
    root = Path(__file__).resolve().parent.parent.parent
    source = Path(os.environ.get("CLOPDIT_FIG_DIR", str(root / "results" / "figures")))
    target = Path(os.environ.get("CLOPDIT_ARTICLE_FIGURES_DIR", str(root / "articles" / "figures")))
    return source, target


def main() -> int:
    default_source, default_target = _default_dirs()
    parser = argparse.ArgumentParser(
        description="Verify article PDF figures and copy them to the article figures directory."
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help=f"Only verify all {_N_FIGURES} PDF figures exist in source dir; do not copy",
    )
    parser.add_argument(
        "--copy",
        action="store_true",
        default=True,
        help="Copy files instead of creating symlinks (default: copy)",
    )
    parser.add_argument(
        "--no-cleanup",
        action="store_true",
        help="Do not remove stale figure artifacts outside the canonical manifest",
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=None,
        help=f"Source directory with generated JPEG/PDF figure pairs (default: {default_source})",
    )
    parser.add_argument(
        "--target-dir",
        type=Path,
        default=None,
        help=f"Target directory for article figures (default: {default_target})",
    )
    args = parser.parse_args()

    source = args.source_dir if args.source_dir is not None else default_source
    target = args.target_dir if args.target_dir is not None else default_target

    if args.check_only:
        print(f"Checking {_N_FIGURES} article figure PDFs in {source}...")
        ok = deliver_figures(source, target, symlink=False, check_only=True)
        if ok:
            print(f"  All {_N_FIGURES} PDF figures present.")
        else:
            print("Run 'bash scripts/regenerate_report.sh' to generate them.", file=sys.stderr)
        return 0 if ok else 1

    print(f"Checking {_N_FIGURES} article figure PDFs in {source}...")
    ok = deliver_figures(
        source,
        target,
        symlink=not args.copy,
        check_only=False,
        cleanup=not args.no_cleanup,
    )
    if not ok:
        print("Run 'bash scripts/regenerate_report.sh' to generate them.", file=sys.stderr)
        return 1
    print(f"  All {_N_FIGURES} PDF figures present.")
    mode = "copied" if args.copy else "symlinked"
    print(f"  {_N_FIGURES} PDF figures {mode} to {target}.")
    print("")
    print(
        f"All {_N_FIGURES} article PDF figures verified and {mode}; "
        f"LaTeX should include the {_ARTICLE_INCLUDE_SUFFIX} assets."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
