#!/usr/bin/env bash
# cleanup_light.sh — Delete regenerable outputs (figures, metrics, reports).
#
# Safe to run at any time. Does NOT touch model weights, cached latents,
# or training logs. Everything removed can be rebuilt via:
#   bash scripts/regenerate_report.sh
#
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "=== CLOP-DiT Light Cleanup ==="
echo "Removing regenerable outputs..."

# Generated figures (PNG/PDF panels, combined report)
rm -rf results/figures/
echo "  ✓ results/figures/"

# Benchmark report (regenerated by model_benchmarking.py)
rm -f results/benchmark_report.json
echo "  ✓ results/benchmark_report.json"

# Diversity diagnostics (regenerated by inference)
rm -f results/diversity_diagnostics.json
echo "  ✓ results/diversity_diagnostics.json"

# Baseline metrics (regenerated by benchmarking)
rm -f results/baseline_metrics.json
echo "  ✓ results/baseline_metrics.json"

# Old standalone figures directory
rm -rf figures/v5_publication/*.png figures/v5_publication/*.pdf 2>/dev/null || true
echo "  ✓ figures/v5_publication/ (PNGs/PDFs)"

# Python caches
find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
find . -name "*.pyc" -delete 2>/dev/null || true
echo "  ✓ __pycache__/ and *.pyc"

# Pytest cache
rm -rf .pytest_cache/
echo "  ✓ .pytest_cache/"

echo ""
echo "Done. Run 'bash scripts/regenerate_report.sh' to rebuild all outputs."
